#!/usr/bin/env bash

# ls
alias ls='ls --sort=extension --color=auto'
alias ll='ls -lh'
alias la='ls -lah'

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ps
alias psg='ps -ef | grep'

# Install and update
alias smi='sudo make install'
